"""Build the UV print and cutting section with the current site's shared components.

Content is retained in uv-content.json; customer source files are not
required to rebuild. Run from any directory with Python's standard library.
"""
from pathlib import Path
from html import escape
import json,re

ROOT=Path(__file__).resolve().parents[1]
DATA=json.loads((ROOT/'uv-content.json').read_text(encoding='utf8'))
CONFIG=json.loads((ROOT/'uv-services.js').read_text(encoding='utf8').split('=',1)[1].strip().rstrip(';'))
STICKERS=json.loads((ROOT/'sticker-services.js').read_text(encoding='utf8').split('=',1)[1].strip().rstrip(';'))
WIDE=json.loads((ROOT/'wide-format-services.js').read_text(encoding='utf8').split('=',1)[1].strip().rstrip(';'))
ARTICLES={a['id']:a for a in json.loads((ROOT/'company-articles.json').read_text(encoding='utf8'))['articles']}
HOME=(ROOT/'index.html').read_text(encoding='utf8')
TEMPLATE=(ROOT/'nakleyki-i-stikery/stikerpaki/index.html').read_text(encoding='utf8')
HEADER=HOME[HOME.index('  <a class="skip-link"'):HOME.index('  <main id="main">')]
FOOTER=TEMPLATE[TEMPLATE.index('<footer'):TEMPLATE.index('</body>')]
HEAD=HOME[HOME.index('<head>')+6:HOME.index('</head>')]
RELATED={s['id']:s for s in DATA}
for id,c in STICKERS.items():RELATED[id]={'id':id,'name':c['name'],'path':c['path'],'hero':c['hero']}
for id,c in WIDE.items():RELATED[id]={'id':id,'name':c['name'],'path':c['path'],'hero':c['hero']}
def icon(name):return f'<span data-icon="{name}"></span>'
def paths(text,prefix):
 return re.sub(r'(href|src)="([^"#]+)"',lambda m:m[0] if re.match(r'^[a-z]+:|^//',m[2]) else f'{m[1]}="{prefix}{m[2]}"',text)
def tag(name,text):return f'<{name}>{escape(text)}</{name}>'
def card(s,prefix):
 return f'<a class="featured-card" href="{prefix}{s["path"]}" aria-label="{escape(s["name"])}"><span class="featured-copy"><span class="featured-name">'+''.join(f'<span class="featured-word">{escape(w)}</span> ' for w in s['name'].split())+f'</span></span><span class="featured-art"><img src="{prefix}assets/{s["hero"]}" alt="{escape(s["name"])}" width="1000" height="1000" loading="lazy"></span></a>'
def save(path,title,description,body,schema,calculator=False):
 prefix='../'*len(Path(path).parts)
 head=paths(HEAD,prefix)
 head=re.sub(r'<script[^>]*type="application/ld\+json"[^>]*>.*?</script>','',head,flags=re.S)
 head=re.sub(r'<meta[^>]*property="og:[^"]*"[^>]*>','',head)
 head=re.sub(r'<title>.*?</title>',f'<title>{escape(title)}</title>',head)
 head=re.sub(r'<meta name="description"[^>]+>',lambda _:f'<meta name="description" content="{escape(description,quote=True)}">',head)
 head=head.replace('noindex, nofollow','index, follow')
 # Root metadata stays independent; new pages have their own canonical.
 head=re.sub(r'<link rel="canonical"[^>]+>','',head)
 resources=f'<link rel="stylesheet" href="{prefix}stickerpacks.css"><link rel="stylesheet" href="{prefix}wide-format.css"><link rel="stylesheet" href="{prefix}uv-print-cut.css">'
 if 'uv-services.js' not in head:
  head=head.replace(f'<script src="{prefix}stickerpack-pricing.js"',f'<script src="{prefix}uv-services.js" defer></script><script src="{prefix}wide-format-pricing.js" defer></script><script src="{prefix}stickerpack-pricing.js"')
 if calculator:resources+=''.join(f'<script src="{prefix}{name}.js" defer></script>' for name in ['copycenter-engine','uv-pricing-data','uv-pricing','uv-sharing','uv-print-cut'])
 head+=resources+f'<link rel="canonical" href="https://text-print.ru/{path}"><script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False).replace('</','<\\/')+'</script>'
 header=paths(HEADER,prefix).replace('href="#main" aria-label="ТЕКСТ — на главную"',f'href="{prefix}" aria-label="ТЕКСТ — на главную"')
 footer=FOOTER.replace('../../',prefix)
 service=next((s for s in DATA if s['path']==path),None)
 attr=f' data-uv-service="{service["id"]}"' if service else ''
 mobile=f'<button class="sp-mobile-total" id="sp-mobile-total" type="button">В корзину · <span id="sp-mobile-price">—</span> {icon("bag")}</button>' if calculator else ''
 html=f'<!doctype html><html lang="ru"><head>{head}</head><body class="stickerpacks-page service-page wide-format-page uv-print-cut-page"{attr}>{header}<main id="main">{body}</main>{mobile}{footer}</body></html>\n'
 html=re.sub(r'(?m)^[ \t]+$', '',html)
 target=ROOT/path/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(html,encoding='utf8')
def crumbs(s,prefix):
 return f'<nav class="sp-breadcrumbs" aria-label="Хлебные крошки"><a href="{prefix}">Главная</a><span>/</span><a href="{prefix}uv-pechat-i-rezka/">UV-печать и резка</a><span>/</span><span aria-current="page">{escape(s["name"])}</span></nav>'
def calc(s):
 return f'''<section class="container sp-section sp-calculator-section" id="calculator" aria-labelledby="sp-calculator-title"><div class="sp-section-title"><h2 id="sp-calculator-title">Выберите нужные параметры</h2><p>Настройте изделие. Стоимость и срок появятся сразу.</p></div><form class="sp-calculator" id="uv-form" novalidate><div class="sp-options-panel"><button type="button" class="icon-button sp-copy-button" id="sp-copy" title="Скопировать параметры и цены" aria-label="Скопировать параметры и цены">{icon('copy')}<span id="sp-copy-status" role="status"></span></button><div class="uv-config-grid" id="uv-fields"></div><fieldset class="uv-quantity-field"><legend>Количество изделий</legend><div class="sp-quantity-stack uv-quantity-stack" id="sp-quantity-options"></div><label class="uv-custom-quantity" id="sp-custom-quantity" hidden>Свой тираж<input type="number" id="sp-quantity" min="1" step="1" inputmode="numeric" aria-describedby="uv-error"></label><p class="sp-field-note">Рядом указана стоимость всего заказа.</p></fieldset><p class="sp-calculator-note">{escape(s['note'])} Минимальный чек — {s['minimum']} ₽.</p><p id="uv-error" class="sp-field-error" role="status" aria-live="polite"></p></div><aside class="sp-result-panel"><label class="sp-file-zone" id="sp-file-zone" for="sp-file">{icon('upload')}<strong id="sp-file-label">Загрузите макет</strong><span>PDF, изображения или исходники · до 100 МБ</span><input type="file" id="sp-file" accept=".pdf,.jpg,.jpeg,.png,.tif,.tiff,.svg,.ai,.eps,.cdr,.psd,.zip"></label><div class="sp-file-tools"><p id="sp-file-status">Можно прикрепить позже в корзине.</p><button type="button" id="sp-remove-file" hidden>Убрать</button></div><label class="sr-only" for="sp-comment">Комментарий к макету</label><textarea id="sp-comment" rows="2" maxlength="2000" placeholder="Комментарий к макету"></textarea><div class="sp-result" aria-live="polite" aria-atomic="true"><div class="sp-result-heading">Ваш заказ <span>× <span id="sp-selected-quantity">—</span></span></div><p id="sp-selected-description"></p><div class="uv-details" id="uv-details"></div><div class="sp-total" id="sp-total">—</div><div class="sp-unit"><span id="sp-unit">—</span> за изделие</div><p class="sp-minimum-note" id="sp-surcharge" hidden></p><div class="sp-deadline">{icon('clock')}<span id="sp-days">—</span></div><small>После полного согласования макета.<br>Срок подтверждаем при оформлении.</small></div><button type="submit" class="button button-primary sp-add-button" id="sp-add">В корзину {icon('bag')}</button><button type="button" class="sp-download" id="sp-download">{icon('download')}Скачать расчёт</button><button type="button" class="text-button wide-manual" id="sp-manual">Запросить индивидуальный расчёт {icon('arrow')}</button><p class="sp-result-disclosure">Макет сохраняется в этом браузере. Отправка в студию — при подготовке запроса.</p></aside></form></section>'''

def build(s):
 p='../../';c=CONFIG[s['id']]
 chips=[('zap','от 1 изделия'),('wide','свой размер'),('palette','яркое изображение' if s['id']!='6.2' else 'чёткий контур'),('shield','проверка макета')]
 benefits=[('wide','Под вашу задачу','Готовый размер'),('layers','Выбор материала','Варианты в калькуляторе'),('palette','Ваше изображение','Для рекламы и интерьера'),('zap','От 1 изделия','Для разных тиражей')]
 hero=f'<section class="container sp-hero-section">{crumbs(s,p)}<div class="sp-hero"><div class="sp-hero-copy"><span class="sp-badge">{escape(s["badge"])}</span><p class="sp-display sp-display-service" aria-hidden="true">{escape(s["display"][0])} <span>{escape(s["display"][1])}</span></p><h1>{escape(s["h1"])}</h1><p class="sp-intro">{escape(s["intro"])}</p><ul class="sp-chips">'+''.join(f'<li>{icon(i)}{escape(t)}</li>' for i,t in chips)+f'</ul><div class="sp-hero-actions"><a class="button button-primary" href="#calculator">Рассчитать стоимость {icon("arrow")}</a><button class="button button-outline" id="sp-hero-upload">{icon("upload")}Загрузить макет</button></div><ul class="sp-hero-benefits"><li>{icon("zap")}Быстрый старт</li><li>{icon("shield")}Проверка макета</li><li>{icon("truck")}Удобный заказ</li></ul></div><div class="sp-hero-art"><img src="{p}assets/{s["hero"]}" alt="Робот ТЕКСТ: {escape(s["name"])}" width="1000" height="1000" fetchpriority="high"></div></div><div class="sp-benefit-grid">'+''.join(f'<article>{icon(i)}<h2>{escape(t)}</h2><p>{escape(d)}</p></article>' for i,t,d in benefits)+'</div></section>'
 production=f'<section class="container sp-section sp-production"><div><span class="sp-overline">ОТ ИДЕИ ДО ГОТОВОГО ИЗДЕЛИЯ</span><h2>Точная работа.<br><span>Внимание к деталям.</span></h2><p>{escape(s["production"])}</p><button class="text-button" data-action="request" data-record="{s["id"]}">Поможем подготовить макет {icon("arrow")}</button></div><ol><li><span>01</span><div><h3>Выберите параметры</h3><p>{escape(s["materials"])}</p></div></li><li><span>02</span><div><h3>Согласуйте макет</h3><p>{escape(s["requirements"])}</p></div></li><li><span>03</span><div><h3>Получите готовый заказ</h3><p>Самовывоз: Барнаул, пр. Строителей, 11. Доставка по России — по согласованию.</p></div></li></ol></section>'
 t=s['technical'];checks=''.join(f'<li>{icon("check")}<span>{escape(item)}</span></li>' for item in t['checks'])
 tech_blocks='<div class="wide-tech-grid">'+''.join(f'<article class="wide-tech-block"><h3>{escape(title)}</h3>{body}</article>' for title,body in [('Файл и технический минимум',tag('p',t['fileSpec'])),('Критично','<ul>'+''.join(tag('li',v) for v in t['critical'])+'</ul>'),('Не делайте так','<ul>'+''.join(tag('li',v) for v in t['mistakes'])+'</ul>'),('Что проверяем перед запуском',tag('p',t['preflight']))])+'</div>'
 preparation=f'<section class="container sp-section wide-preparation" aria-labelledby="sp-requirements-title"><div class="sp-requirements"><div>{icon("document")}<h2 id="sp-requirements-title">Макет, с которым всё получится</h2><p>{escape(t["send"])}</p></div><a class="button button-outline" href="{p}requirements/#requirement-{s["id"].replace(".","-")}">Требования к макетам {icon("arrow")}</a></div>{tech_blocks}<h3 class="wide-checklist-title">Проверьте перед отправкой</h3><ul class="wide-checklist">{checks}</ul><p class="wide-example">{escape(t["example"])}</p>{tag("p",t["note"]) if t.get("note") else ""}</section>'
 linked=[RELATED[id] for id in s['related'] if id in RELATED]
 if len(linked)<3:linked += [other for other in DATA if other['id'] not in [s['id'],*[r['id'] for r in linked]]][:3-len(linked)]
 related='<section class="container sp-section"><div class="sp-section-title sp-title-left"><h2>Для других задач</h2></div><div class="featured-grid sp-related">'+''.join(card(r,p) for r in linked)+'</div></section>'
 articles=[ARTICLES[id] for id in s['articleIds'] if id in ARTICLES]
 reading='<section class="container sp-section wide-reading"><div class="sp-section-title sp-title-left"><h2>Полезно перед заказом</h2></div><div class="wide-reading-links">'+''.join(f'<a class="wide-reading-link" href="{p}{a["path"]}">{icon("document")}<span>{escape(a["title"])}</span>{icon("arrow")}</a>' for a in articles)+'</div></section>'
 faq='<section class="container lower-section home-faq-section sp-faq" id="faq" aria-labelledby="sp-faq-title"><h2 id="sp-faq-title">Вопросы об услуге «'+escape(s['name'])+'»</h2><div class="home-faq-stage"><div class="home-faq-content"><div class="faq-list">'+''.join(f'<details><summary>{escape(f["q"])}{icon("plus")}</summary>{tag("p",f["a"])}</details>' for f in s['faq'])+f'</div></div><img class="faq-mascot" src="{p}assets/faq-peeking-robot.webp" alt="Робот ТЕКСТ рядом с ответами на вопросы" width="400" height="600" loading="lazy"></div><aside class="faq-help"><div class="faq-help-copy"><h3>Не нашли ответ?</h3><p>Позвоните нам или напишите — поможем разобраться с заказом.</p></div><div class="faq-help-actions"><a class="button button-primary" href="tel:+79236547896">Позвонить {icon("phone")}</a><button class="button button-outline" data-action="contacts">Написать нам {icon("message")}</button></div></aside></section>'
 seo='<section class="container lower-section sp-seo"><div class="sp-seo-card"><h2>'+escape(s['name'])+' в типографии «ТЕКСТ»</h2><div class="sp-seo-body">'+''.join(tag('p',x) for x in s['seo'].split('\n\n'))+'</div><div class="sp-seo-related"><p>Студия печати в Барнауле, проспект Строителей, 11. '+f'<a href="{p}contacts/">Контакты</a> · <a href="{p}dostavka-i-oplata/">Доставка</a> · <a href="{p}company/payment/">Оплата</a>'+'</p></div></div></section>'
 schema={'@context':'https://schema.org','@graph':[{'@type':'Service','name':s['name'],'url':'https://text-print.ru/'+s['path'],'serviceType':s['name'],'areaServed':'Барнаул','provider':{'@type':'Organization','name':'ТЕКСТ','url':'https://text-print.ru/'}},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Главная','item':'https://text-print.ru/'},{'@type':'ListItem','position':2,'name':'UV-печать и резка','item':'https://text-print.ru/uv-pechat-i-rezka/'},{'@type':'ListItem','position':3,'name':s['name'],'item':'https://text-print.ru/'+s['path']}]}]}
 save(s['path'],s['title'],s['description'],hero+calc(s)+production+preparation+related+reading+'<div class="lower-home sp-lower">'+faq+seo+'</div>',schema,True)
for s in DATA:build(s)
p='../'
category=f'<section class="container sp-hero-section"><nav class="sp-breadcrumbs" aria-label="Хлебные крошки"><a href="{p}">Главная</a><span>/</span><span aria-current="page">UV-печать и резка</span></nav><div class="sp-hero"><div class="sp-hero-copy"><span class="sp-badge">От вашего макета — к готовому изделию</span><p class="sp-display sp-display-service" aria-hidden="true">UV-печать <span>и резка</span></p><h1>UV-печать, лазерная и плоттерная резка в Барнауле</h1><p class="sp-intro">Изображения на листовых материалах, точная резка и гравировка. Таблички, брелоки, шильды и номерки — выберите услугу и рассчитайте свои параметры.</p><div class="sp-hero-actions"><a class="button button-primary" href="#services">Выбрать услугу {icon('arrow')}</a><button class="button button-outline" data-action="contacts">Помощь с заказом {icon('message')}</button></div></div><div class="sp-hero-art"><img src="{p}assets/{DATA[0]['hero']}" alt="Робот ТЕКСТ с изделием прямой UV-печати" width="1000" height="1000" fetchpriority="high"></div></div></section><section class="container sp-section" id="services"><div class="sp-section-title sp-title-left"><h2>Что будем создавать?</h2><p>У каждой услуги — свои материалы, требования и онлайн-калькулятор.</p></div><div class="featured-grid wide-category-grid">'+''.join(card(s,p) for s in DATA)+'</div></section><section class="container sp-section sp-requirements"><div>'+icon('document')+f'<h2>Макет для печати, резки и гравировки</h2><p>Подготовьте файл в готовом размере. Разделите изображение, белый слой, контур резки и гравировку — поможем проверить его перед производством.</p></div><a class="button button-outline" href="{p}requirements/">Требования к макетам {icon("arrow")}</a></section>'
save('uv-pechat-i-rezka/','UV-печать и резка в Барнауле — услуги и цены | ТЕКСТ','UV-печать, лазерная и плоттерная резка, гравировка, таблички, брелоки, шильды и гардеробные номерки. Онлайн-расчёт в студии ТЕКСТ.',category,{'@context':'https://schema.org','@type':'CollectionPage','name':'UV-печать и резка','url':'https://text-print.ru/uv-pechat-i-rezka/','hasPart':[{'@type':'WebPage','name':s['name'],'url':'https://text-print.ru/'+s['path']} for s in DATA]})
print('Built nine UV service pages and the category page.')
